site_name: Grupo-8-JurisSocial-docs

repo_name: unb-Sistemas-de-Machine-learning/Grupo-8-JurisSocial-docs
repo_url: https://github.com/unb-Sistemas-de-Machine-learning/Grupo-8-JurisSocial-docs

theme:
  name: material
  palette: 
    primary: deep purple
    accent: aliceblue
  features:
    - navigation.tabs
    - navigation.top
  
nav: 
  - Início: index.md
  - Artefatos:
    - Visão do Produto: Artefatos/visaoProduto.md
    - Ferramentas: Artefatos/ferramentas.md
    - Diretórios: Artefatos/repositorio.md
    - Requisitos: Artefatos/requisitos.md
    - Mapeamento de Dados: Artefatos/mapeamentoDados.md
    - Requisitos ML: Artefatos/requisitosML.md
    - História de Usuário: Artefatos/historiaUsuario.md
    - Cronograma: Artefatos/cronograma.md
    - Engenharia de Dados: Artefatos/engenhariaDados.md
    - Arquitetura: Artefatos/arquitetura.md
    - Escolha e Justificativa: Artefatos/justificativa-escolha.md
    - Resultados: Artefatos/resultados.md

